### ISSUE TITLE
More a question than an issue but...

### ISSUE THREAD

**Issue by whitedavidp** [RoelVB/powerchute-personal-notifications#1]
Greetings from Seattle, WA USA and thanks for this...

I am wondering if it can help me to manually trigger a self-test of my APC ES-550 UPS?

I note that Windows periodically shows me a notification of an event from the APC UPS Server source that reads something like self-test completed. I have seen this on multiple computers using same/similar UPS units.

I would like to be able to run the test on my own schedule (in addition to whatever schedule APC Power Chute is using). I found this and was hoping I might be able to use it to accomplish my goals.

Any tips/suggestions?

Thanks!

**Comment by RoelVB** [comment]
Hi there,

This project doesn't really interact with APC's software. It only responds to its events.
So unfortunately I don't know how to help with your case.

**Comment by whitedavidp** [comment]
Well, thanks anyhow.
